#!/usr/bin/env bash
set -euo pipefail

# PQ-NAS Safe Uninstaller
# - Removes: systemd unit, binaries, /opt/pqnas assets (static + bundled dna lib)
# - Optionally removes: nginx PQ-NAS site config if it looks like ours
# - Keeps: /srv/pqnas (DATA), /etc/pqnas (CONFIG)
#
# Usage:
#   sudo ./uninstall.sh
#
# Notes:
# - This is intentionally conservative.
# - It will NOT delete user data in the NAS storage root.

say() { echo "[*] $*"; }
warn() { echo "[!] $*" >&2; }
die() { echo "[ERROR] $*" >&2; exit 1; }

need_root() {
  if [[ "${EUID:-$(id -u)}" -ne 0 ]]; then
    die "Run as root: sudo $0"
  fi
}

have_cmd() { command -v "$1" >/dev/null 2>&1; }

read_pqnas_root_from_env() {
  local env="/etc/pqnas/pqnas.env"
  if [[ -f "$env" ]]; then
    # shellcheck disable=SC1090
    source "$env" || true
    if [[ -n "${PQNAS_ROOT:-}" ]]; then
      echo "$PQNAS_ROOT"
      return 0
    fi
  fi
  echo ""
}

stop_disable_service() {
  if have_cmd systemctl; then
    if systemctl list-unit-files | rg -q '^pqnas\.service'; then
      say "Stopping pqnas.service (if running)…"
      systemctl stop pqnas.service >/dev/null 2>&1 || true

      say "Disabling pqnas.service…"
      systemctl disable --now pqnas.service >/dev/null 2>&1 || true
    fi
  fi
}

kill_leftover_processes() {
  # best-effort; don't fail if pkill missing or nothing matches
  if have_cmd pkill; then
    say "Killing leftover pqnas_server processes (best effort)…"
    pkill -f '^/usr/local/bin/pqnas_server$' >/dev/null 2>&1 || true
    pkill -f 'pqnas_server' >/dev/null 2>&1 || true
  fi
}

remove_systemd_unit() {
  local unit="/etc/systemd/system/pqnas.service"
  if [[ -f "$unit" ]]; then
    say "Removing systemd unit: $unit"
    rm -f "$unit"
    if have_cmd systemctl; then
      say "systemd daemon-reload…"
      systemctl daemon-reload >/dev/null 2>&1 || true
      systemctl reset-failed >/dev/null 2>&1 || true
    fi
  else
    say "systemd unit not found (ok): $unit"
  fi
}

remove_binaries() {
  local bin_dir="/usr/local/bin"
  local files=(
    "$bin_dir/pqnas_server"
    "$bin_dir/pqnas_keygen"
    "$bin_dir/pqnas_server.bak"
    "$bin_dir/pqnas_keygen.bak"
    "$bin_dir/pqnas_server.new"
    "$bin_dir/pqnas_keygen.new"
  )

  say "Removing binaries from $bin_dir (if present)…"
  for f in "${files[@]}"; do
    if [[ -e "$f" ]]; then
      rm -f "$f"
      say "  removed: $f"
    fi
  done
}

remove_opt_assets() {
  # These are shipped assets; safe to remove.
  local static="/opt/pqnas/static"
  local dnalib="/opt/pqnas/lib/dna/libdna_lib.so"
  local dnadir="/opt/pqnas/lib/dna"
  local libroot="/opt/pqnas/lib"

  if [[ -d "$static" ]]; then
    say "Removing shipped static assets: $static"
    rm -rf "$static"
  else
    say "Static assets not found (ok): $static"
  fi

  if [[ -f "$dnalib" ]]; then
    say "Removing shipped DNA engine lib: $dnalib"
    rm -f "$dnalib"
  else
    say "DNA engine lib not found (ok): $dnalib"
  fi

  # clean empty directories (only if empty)
  if [[ -d "$dnadir" ]] && rmdir "$dnadir" 2>/dev/null; then
    say "Removed empty dir: $dnadir"
  fi
  if [[ -d "$libroot" ]] && rmdir "$libroot" 2>/dev/null; then
    say "Removed empty dir: $libroot"
  fi
}

nginx_remove_site_if_ours() {
  # ONLY remove nginx config if it looks generated by our installer.
  # We do NOT uninstall nginx itself.
  if ! have_cmd nginx || ! have_cmd systemctl; then
    say "nginx not installed (or systemctl missing) — skipping nginx cleanup."
    return 0
  fi

  local candidates=(
    "/etc/nginx/sites-available/pqnas"
    "/etc/nginx/conf.d/pqnas.conf"
  )

  local found=""
  for c in "${candidates[@]}"; do
    if [[ -f "$c" ]]; then
      found="$c"
      break
    fi
  done

  if [[ -z "$found" ]]; then
    say "No pqnas nginx config found (ok)."
    return 0
  fi

  # Check for our marker line used in installer:
  # "# PQ-NAS nginx reverse proxy (HTTP-only)"
  if ! rg -q 'PQ-NAS nginx reverse proxy' "$found"; then
    warn "Found nginx config $found but it does not look like PQ-NAS installer-generated. Leaving it untouched."
    return 0
  fi

  say "Removing nginx config: $found"
  rm -f "$found"

  # sites-enabled symlink cleanup
  if [[ -L "/etc/nginx/sites-enabled/pqnas" || -e "/etc/nginx/sites-enabled/pqnas" ]]; then
    say "Removing nginx enabled link: /etc/nginx/sites-enabled/pqnas"
    rm -f "/etc/nginx/sites-enabled/pqnas"
  fi

  say "nginx -t …"
  if nginx -t >/dev/null 2>&1; then
    say "Reloading nginx…"
    systemctl reload nginx >/dev/null 2>&1 || true
  else
    warn "nginx -t failed after removal; not reloading. Please check nginx config."
  fi
}

print_keep_notes() {
  local root
  root="$(read_pqnas_root_from_env)"
  if [[ -n "$root" ]]; then
    echo
    say "Kept DATA (unchanged): $root"
  else
    echo
    say "Kept DATA (unchanged): /srv/pqnas  (default; mountpoint depends on your install)"
  fi

  echo
  say "Kept CONFIG (unchanged): /etc/pqnas/"
  say "  - If you reinstall later, your config and users/shares will still be there."
}

confirm() {
  echo
  echo "This will perform a SAFE uninstall of PQ-NAS:"
  echo "  - stop/disable pqnas.service"
  echo "  - remove /etc/systemd/system/pqnas.service"
  echo "  - remove /usr/local/bin/pqnas_server + pqnas_keygen"
  echo "  - remove /opt/pqnas/static + /opt/pqnas/lib/dna/libdna_lib.so"
  echo "  - optionally remove installer-generated nginx pqnas site config"
  echo
  echo "It will NOT delete:"
  echo "  - /srv/pqnas (your NAS data)"
  echo "  - /etc/pqnas (your config)"
  echo
  read -r -p "Type exactly: UNINSTALL  > " ans
  [[ "$ans" == "UNINSTALL" ]] || die "Confirmation did not match. Nothing done."
}

main() {
  need_root
  confirm

  stop_disable_service
  kill_leftover_processes
  remove_systemd_unit
  remove_binaries
  remove_opt_assets
  nginx_remove_site_if_ours

  echo
  say "✅ Safe uninstall complete."
  print_keep_notes
}

main "$@"
