#!/usr/bin/env python3
from pathlib import Path
import json

ROOT = Path(__file__).resolve().parents[1]
ICON_DIR = ROOT / "apps" / "bundled" / "filemgr" / "src" / "www" / "icons" / "filetypes"

ANDROID_ROOT = Path.home() / "AndroidStudioProjects" / "PQNAS"
OUT = ANDROID_ROOT / "app" / "src" / "main" / "java" / "com" / "pqnas" / "mobile" / "files" / "FileTypeIcons.kt"

PACKAGE = "com.pqnas.mobile.files"

def kotlin_string_literal(s: str) -> str:
    return json.dumps(s, ensure_ascii=False)

def main() -> int:
    if not ICON_DIR.is_dir():
        raise SystemExit(f"Icon directory not found: {ICON_DIR}")

    if not ANDROID_ROOT.is_dir():
        raise SystemExit(f"Android project not found: {ANDROID_ROOT}")

    icons = {}
    for p in sorted(ICON_DIR.glob("*.svg")):
        if not p.is_file():
            continue
        icons[p.stem.lower()] = p.read_text(encoding="utf-8")

    required = ["default", "folder"]
    missing = [k for k in required if k not in icons]
    if missing:
        raise SystemExit(f"Missing required icons: {', '.join(missing)}")

    OUT.parent.mkdir(parents=True, exist_ok=True)

    lines = []
    lines.append("// Auto-generated by tools/generate_android_filetype_icons.py")
    lines.append("// Do not edit by hand.")
    lines.append(f"package {PACKAGE}")
    lines.append("")
    lines.append("import android.net.Uri")
    lines.append("import com.pqnas.mobile.api.FileItemDto")
    lines.append("")
    lines.append("object FileTypeIcons {")
    lines.append("    private val icons: Map<String, String> = mapOf(")

    entries = list(sorted(icons.items()))
    for i, (key, value) in enumerate(entries):
        comma = "," if i < len(entries) - 1 else ""
        lines.append(f"        {kotlin_string_literal(key)} to {kotlin_string_literal(value)}{comma}")

    lines.append("    )")
    lines.append("")
    lines.append("    private fun extOf(name: String): String {")
    lines.append('        val n = name.substringAfterLast("/", name).lowercase()')
    lines.append('        val dot = n.lastIndexOf(\'.\')')
    lines.append('        if (dot <= 0 || dot == n.length - 1) return "default"')
    lines.append("        return n.substring(dot + 1)")
    lines.append("    }")
    lines.append("")
    lines.append("    fun svgFor(item: FileItemDto): String {")
    lines.append('        if (item.type == "dir") return icons["folder"] ?: ""')
    lines.append("        val ext = extOf(item.name)")
    lines.append('        return icons[ext] ?: icons["default"].orEmpty()')
    lines.append("    }")
    lines.append("")
    lines.append("    fun dataUriFor(item: FileItemDto): String {")
    lines.append('        return "data:image/svg+xml;utf8," + Uri.encode(svgFor(item))')
    lines.append("    }")
    lines.append("}")
    lines.append("")

    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"[OK] wrote {OUT} ({len(icons)} icons)")
    return 0

if __name__ == "__main__":
    raise SystemExit(main())