#!/usr/bin/env python3
from pathlib import Path
import json

ROOT = Path(__file__).resolve().parents[1]
ICON_DIR = ROOT / "apps" / "bundled" / "filemgr" / "src" / "www" / "icons" / "filetypes"
OUT = ROOT / "apps" / "bundled" / "filemgr" / "src" / "www" / "filetype_icons.js"

def main() -> int:
    if not ICON_DIR.is_dir():
        raise SystemExit(f"Icon directory not found: {ICON_DIR}")

    icons = {}
    for p in sorted(ICON_DIR.glob("*.svg")):
        if not p.is_file():
            continue
        icons[p.stem] = p.read_text(encoding="utf-8")

    required = ["default", "folder"]
    missing = [k for k in required if k not in icons]
    if missing:
        raise SystemExit(f"Missing required icons: {', '.join(missing)}")

    js = []
    js.append("// Auto-generated by tools/generate_filetype_icon_map.py")
    js.append("// Do not edit by hand.")
    js.append("(function(){")
    js.append('  "use strict";')
    js.append(f"  window.PQNAS_FILE_ICONS = {json.dumps(icons, ensure_ascii=False, separators=(',', ':'))};")
    js.append("})();")
    js.append("")

    OUT.write_text("\n".join(js), encoding="utf-8")
    print(f"[OK] wrote {OUT} ({len(icons)} icons)")
    return 0

if __name__ == "__main__":
    raise SystemExit(main())